#BNF+IAT 1.0 UTF-8;
!grammar call;

/*!slot <want>;
!slot <dialpre>;
!slot <dialsuf>;
!slot <contact>;

!start <callstart>;
<callstart>:[<want>]<dial>;

<want>:我想|我要|请|帮我|我想要|请帮我|要;

<dial>:<dialpre><contact>[<dialsuf>];

<dialpre>:打电话给!id(10001)|打给!id(10001)|拨打!id(10001)|拨打电话给!id(10001)|呼叫!id(10001)|
打一个电话给!id(10001)|打个电话给!id(10001)|给|拨通!id(10001)|
接通!id(10001)|呼叫!id(10001)|呼叫给!id(10001)|打!id(10001);

<dialsuf>:打电话!id(10001)|打个电话!id(10001)|打一个电话!id(10001)|
拨打电话!id(10001)|拨电话!id(10001)|0拨个电话!id(10001)|呼个电话!id(10001)|
的电话!id(10001)|的号码!id(10001)|的手机!id(10001)|
的办公电话!id(10001)|的移动号码!id(10001)|的联通号码!id(10001)|
的电信号码!id(10001)|客服电话!id(10001);

<contact>:丁伟;*/


!slot <todo>;
!slot <order>;

!start <t214>;
<t214>:[<todo>]<order>;

<todo>:运行!id(21301)|执行!id(21301)|进行!id(21301)|
回去!id(21302)|返回!id(21302);

<order>:人脸检测!id(21401)|检测人脸!id(21401)|
面部识别!id(21402)|识别身份!id(21402)|人脸识别!id(21402)|身份识别!id(21402)|
没电了!id(21403)|充电!id(21403)|快没电了!id(21403);



